Fix a type error in the `tinymce-controller.js` (see #8611)
Description
-----------

Fixes the following error when switching content element type for example from text to image.
Object.prototype.hasOwn does not exist. 
Object.hasOwn (preferred according to MDN) or Object.prototype.hasOwnProperty should be used instead.

Only 5.6 contains the faulty code, that's why this PR is targeted against 5.6.

```
TypeError: t.plugins.hasOwn is not a function
    at t.leave (backend.9b92fb52.js:25:55357)
    at y.invokeWithEvent (backend.9b92fb52.js:25:136579)
    at y.handleEvent (backend.9b92fb52.js:25:135911)
    at n.handleEvent (backend.9b92fb52.js:25:130791)
    at u (backend.9b92fb52.js:2:7395)
    at Object.notifyApplicationBeforeVisitingLocation (backend.9b92fb52.js:16:40046)
    at Object.applicationAllowsVisitingLocation (backend.9b92fb52.js:16:39799)
    at Object.allowsVisitingLocationWithAction (backend.9b92fb52.js:16:37864)
    at it.proposeVisit (backend.9b92fb52.js:16:20279)
    at it.formSubmissionSucceededWithResponse (backend.9b92fb52.js:16:21345)
```

Commits
-------

6849f37f Fix TypeError in tinymce-controller.js