Allow prefilling of scripts and stylesheets (see #1153).
Description
-----------

IMO the backend template should only append variables and not kill values set by the developer in the parse method but rather append to them.

This way one may define custom stylesheets and scripts from within an custom backend controller that will not get overridden by the template.

I am using this in a custom backend controller template based upon `be_main.html.twig`:
```twig
{{ render_contao_backend_template({
    main: block('main'),
    error: block('error'),
    headline: block('headline'),
    stylesheets: block('stylesheets'),
    javascripts: block('javascripts'),
    mootools: block('mootools')
}) | raw }}

{# 
  Here we generate the stylesheets to be added to be_main instead of adding 
  stuff to $GLOBALS['TL_CSS'] within a Symfony controller.
#}
{% block stylesheets %}
    {% for stylesheet in stylesheets %}
        <link rel="stylesheet" href="{{ stylesheet }}">
    {% endfor %}
{% endblock %}
{# 
  Here we generate the javascripts to be added to be_main instead of adding 
  stuff to $GLOBALS['TL_JAVASCRIPT'] within a Symfony controller.
  TODO: add support for "async" here.
#}
{% block javascripts %}
    {% for javascript in javascripts %}
        <script src="{{ javascript }}"></script>
    {% endfor %}
{% endblock %}
{# 
  Here we have the mootools scripts to be added to be_main instead of adding 
  stuff to $GLOBALS['TL_MOOTOOLS'] within a Symfony controller.
#}
{% block mootools %}
    {% for mootool in mootools %}
        {{ mootool }}
    {% endfor %}
{% endblock %}
....
```

So we have now:
- three added dots in this PR
- a custom twig template

And I am able to do anything in a custom controller without any reference to `$GLOBALS`

@contao/developers what do you think? Shall we also expand the shipped template then?

Commits
-------

a3b68142 Merge branch 'hotfix/4.4.7'
dce3cd9a Allow prefilling of scripts and stylesheets