[Core] Also check innodb_file_per_table in the DCA schema provider (see #103)
Description
-----------

With @Toflar we had troubles updating the Contao 4.5 database to 4.6 and being more explicit it was about the index column size being too large:

```
Message: "An exception occurred while executing 'ALTER TABLE tl_files ENGINE = InnoDB ROW_FORMAT = DYNAMIC':  SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
```

It's not only the `tl_files.path` index that was causing the error but also all the others with length of 255, e.g. `tl_member.email` caused this error:

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE tl_member CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci':
PDOException: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
```

We have dropped faulty indexes and then the switch to InnoDB engine was successful. However when Contao tried to re-create them, the error arose again. What we have found out is that for the MySQL version we are using (maybe for others as well, not sure about that) the `innodb_file_per_table` variable must be enabled for large indexes. Thus if it is not, the default index length should be 767 bytes.

Our MySQL server version is: 5.5.5-10.0.34-MariaDB

Also see: https://stackoverflow.com/a/43403017/3628692

**I will add the necessary unit tests if you first approve this commit.**

Commits
-------

e0000c17 Check for innodb_file_format only if the innodb_file_per_table variable is enabled
ad06e5fc Added the missing unit tests
55e1c049 Purge the duplicate tests
c49cdc53 Return early if the innodb_file_per_table option is disabled